In [11]:
import numpy as np
from numpy import linalg as LA

# 3. Metoda potęgowa obliczania wartości własnych macierzy $\|A\|$ dla macierzy 3x3 (wykład 4 slajd 23)

Piotr Kędziora

In [12]:
A = [[4, 9, 2],
     [3, 5, 7],
     [8, 1, 6]]

In [13]:
print('\n'.join([''.join(['{:4}'.format(item) for item in row]) 
      for row in A]))

   4   9   2
   3   5   7
   8   1   6


In [14]:
z_1 = [[1],[1], [1]]

In [15]:
print('\n'.join([''.join(['{:4}'.format(item) for item in row]) 
      for row in z_1]))

   1
   1
   1


In [16]:
A = np.matrix(A)

### zaczynamy iterację pierwszą

In [17]:
z_1 = np.matrix(z_1)
print(z_1)

[[1]
 [1]
 [1]]


In [18]:
w_1 = A * z_1
print(w_1)

[[15]
 [15]
 [15]]


In [19]:
l_1 = float(max(abs(w_1)))
print(l_1)

15.0


In [20]:
e_1 = w_1 - l_1*z_1
e_1 = LA.norm(e_1)
print(e_1)

0.0


### iteracja druga

In [21]:
z_2 = w_1/l_1
print(z_2)

[[1.]
 [1.]
 [1.]]


In [22]:
w_2 = A*z_2
print(w_2)

[[15.]
 [15.]
 [15.]]


In [23]:
l_2 = float(max(abs(w_2)))
print(l_2)

15.0


In [24]:
e_2 = w_2 - l_2*z_2
e_2 = LA.norm(e_2)
print(e_2)

0.0


### iteracja trzecia

In [25]:
z_3 = w_2/l_2
print(z_3)

[[1.]
 [1.]
 [1.]]


In [26]:
w_3 = A*z_3
print(w_3)

[[15.]
 [15.]
 [15.]]


In [27]:
l_3 = float(max(abs(w_3)))
print(l_3)

15.0


In [28]:
e_3 = w_3 - l_3*z_3
e_3 = LA.norm(e_3)
print(e_3)

0.0


### iteracja czwarta

In [29]:
z_4 = w_3/l_3
print(z_4)

[[1.]
 [1.]
 [1.]]


In [30]:
w_4 = A*z_4
print(w_4)

[[15.]
 [15.]
 [15.]]


In [31]:
l_4 = float(max(abs(w_4)))
print(l_4)

15.0


In [32]:
e_4 = w_4 - l_4*z_4
e_4 = LA.norm(e_4)
print(e_4)

0.0


### iteracja piąta

In [33]:
z_5 = w_4/l_4
print(z_5)

[[1.]
 [1.]
 [1.]]


In [34]:
w_5 = A*z_5
print(w_5)

[[15.]
 [15.]
 [15.]]


In [35]:
l_5 = float(max(abs(w_5)))
print(l_5)

15.0


In [36]:
e_5 = w_5 - l_5*z_5
e_5 = LA.norm(e_5)
print(e_5)

0.0


## ROZWIĄZANIE W PĘTLI:

In [37]:
A = [[2, -1, 0],
     [-1, 2, -1],
     [0, -1, 2]]

In [38]:
z_1 = [[1],[1], [1]]

In [39]:
A = np.matrix(A)
z = np.matrix(z_1)

In [41]:
while 1:
    print ("petla")
    w = A*z
    l = float(max(abs(w)))
    e = w - l*z
    e = LA.norm(e)
    if e<0.1:
        print (l)
        print (z)
        break
    z = w/l

petla
3.428571428571429
[[ 0.71428571]
 [-1.        ]
 [ 0.71428571]]
