In [1]:
import numpy as np
from numpy import linalg as LA
from math import sqrt

np.set_printoptions(suppress=True, precision=3)

# 2. Algorytm obliczania singular value decomposition (SVD) dla macierzy $\|A\|$ dla macierzy 2x3

Piotr Kędziora

In [2]:
def singular_values(A):
    w, _ = LA.eig(A @ A.T)
    sig = map(lambda x: sqrt(x), w)
    return sorted(sig, reverse=True)

In [3]:
def eigenvectors(M, vertical=False):
    w, v = LA.eig(M)
    i = np.argsort(w)[::-1]
    if vertical:
        return v[i]
    else:
        return v[:,i]

In [4]:
def svd(A, eps=0.000001):
    S = np.zeros((2, 3))
    sig = singular_values(A)
    S[0,0] = sig[0]
    S[1,1] = sig[1]
    
    U = eigenvectors(A @ A.T, vertical=True)
    V = eigenvectors(A.T @ A)
    
    i_u = [[], 0, 1, [0, 1]]
    j_v = [[], 0, 1, 2, [0, 1], [0, 2], [1, 2], [0, 1, 2]]

    for i in i_u:
        for j in j_v:
            U[i] = -U[i]
            V[:,j] = -V[:,j]
           
            if LA.norm(U @ S @ V.T - A) < eps:
                return U, S, V
            
            U[i] = -U[i]
            V[:,j] = -V[:,j]
    raise Exception('Error')

In [5]:
A = np.array([[1, 2, 0], [2, 0, 2]])
print('A')
print(A)
print('=====')

U, S, V = svd(A)
print('U')
print(U)
print('S')
print(S)
print('V')
print(V)
print('=====')

print('A')
print(U @ S @ V.T)

A
[[1 2 0]
 [2 0 2]]
=====
U
[[-0.447  0.894]
 [-0.894 -0.447]]
S
[[3. 0. 0.]
 [0. 2. 0.]]
V
[[-0.745  0.     0.667]
 [-0.298  0.894 -0.333]
 [-0.596 -0.447 -0.667]]
=====
A
[[ 1.  2. -0.]
 [ 2.  0.  2.]]
